<?php

function london_underground_station_array() {
  $array = array(
 'Acton Town (Piccadilly, District Lines; Zone 3)',
 'Aldgate (Metropolitan Line; Zone 1)',
 'Aldgate East (Hammersmith & City, District Lines; Zone 1)',
 'All Saints (DLR (Stratford Branch); Zone 2)',
 'Alperton (Piccadilly Line; Zone 4)',
 'Amersham (Metropolitan Line; Zone D)',
 'Angel (Northern Line; Zone 1)',
 'Archway (Northern Line; Zones 2/3)',
 'Arnos Grove (Piccadilly Line; Zone 4)',
 'Arsenal (Piccadilly Line; Zone 2) ',
 'Baker Street (Metropolitan, Jubliee, Bakerloo, Circle, Hammersmith & City Lines; Zone 1)',
 'Balham (Northern Line; Zone 3)',
 'Bank (Waterloo & City, Central, Northern Lines, DLR (Bank branch); Zone 1)',
 'Barbican (Circle, Metropolitan, Hammersmith & City Lines; Zone 1)',
 'Barking (District Line; Zone 4)',
 'Barkingside (Central Line; Zone 5)',
 'Barons Court (Piccadilly, District Lines; Zone 2)',
 'Bayswater (Circle, District Lines; Zone 1)',
 'Beckton (DLR (Beckton branch); Zone 3)',
 'Beckton Park (DLR (Beckton branch); Zone 3)',
 'Becontree (District Line; Zone 5)',
 'Belsize Park (Northern Line; Zone 2)',
 'Bermondsey (Jubilee Line; Zone 2)',
 'Bethnal Green (Circle Line; Zone 2)',
 'Blackfriars (Circle, District Lines; Zone 1)',
 'Blackhorse Road (Victoria Line; Zone 3)',
 'Blackwall (DLR (Beckton branch); Zone 2)',
 'Bond Street (Jubilee, Central Lines; Zone 1)',
 'Borough (Northern Line; Zone 1)',
 'Boston Manor (Piccadilly Line; Zone 4)',
 'Bounds Green (Piccadilly Line; Zones 3/4)',
 'Bow ChurchDLR (Stratford Branch); Zone 2)',
 'Bow Road (Hammersmith & City, District Lines; Zone 2)',
 'Brent Cross (Northern Line; Zone 3)',
 'Brixton (Victoria Line; Zone 2)',
 'Bromley-by-Bow (Hammersmith & City, District Lines; Zones 2/3)',
 'Buckhurst Hill (Central Line; Zone 5)',
 'Burnt Oak (Northern Line; Zone 4) ',
 'Caledonian Road (Piccadilly Line; Zone 2)',
 'Camden Town (Northern Line; Zone 2)',
 'Canada Water (Jubilee, East London Lines; Zone 2)',
 'Canary Wharf (Jubilee Line, DLR (Lewisham Branch); Zone 2)',
 'Canning Town (Jubilee Line, DLR (Beckton Branch); Zone 3)',
 'Cannon Street (Circle, District Lines; Zone 1)',
 'Canons Park (Jubilee Line; Zone 5)',
 'Chalfont & Latimer (Metropolitan Line; Zone C)',
 'Chalk Farm (Northern Line; Zone 2)',
 'Chancery Lane (Central Line; Zone 1)',
 'Charing Cross (Northern, Bakerloo Lines; Zone 1)',
 'Chesham (Metropolitan Line; Zone D)',
 'Chigwell (Central Line; Zone 5)',
 'Chiswick Park (District Line; Zone 3)',
 'Chorleywood (Metropolitan Line; Zone B)',
 'Clapham Common (Northern Line; Zone 2)',
 'Clapham North (Northern Line; Zone 2)',
 'Clapham South (Northern Line; Zones 2/3)',
 'Cockfosters (Piccadilly Line; Zone 5)',
 'Colindale (Northern Line; Zone 4)',
 'Colliers Wood (Northern Line; Zone 3)',
 'Covent Garden (Piccadilly Line; Zone 1)',
 'Crossharbour & London ArenaDLR (Lewisham Branch); Zone 2)',
 'Croxley (Metropolitan Line; Zone A)',
 'Custom House (DLR (Beckton Branch); Zone 3)',
 'Cutty Sark (DLR (Lewisham Branch); Zones 2/3)',
 'Cyprus (DLR (Beckton Branch); Zone 3) ',
 'Dagenham East (District Line; Zone 5)',
 'Dagenham Heathway (District Line; Zone 5)',
 'Debden (Central Line; Zone 6)',
 'Deptford Bridge (DLR (Lewisham Branch); Zones 2/3)',
 'Devons RoadDLR (Stratford Branch); Zone 2)',
 'Dollis Hill (Jubilee Line; Zone 3) ',
 'Ealing Broadway (Central, District Lines; Zone 3)',
 'Ealing Common (Piccadilly, District Lines; Zone 3)',
 'Earl\'s Court (Piccadilly, District Lines; Zones 1/2)',
 'East Acton (Central Line; Zone 2)',
 'East Finchley (Northern Line; Zone 3)',
 'East Ham (Hammersmith & City, District Lines; Zones 3/4)',
 'East India (DLR (Beckton Branch); Zones 2/3)',
 'East Putney (District Line; Zones 2/3)',
 'Eastcote (Piccadilly, Metropolitan Lines; Zone 5)',
 'Edgware (Northern Line; Zone 5)',
 'Edgware Road (Bakerloo , District, Hammersmith & City, Circle Lines; Zone 1)',
 'Elephant & Castle (Bakerloo, Northern Lines; Zones 1/2)',
 'Elm Park (District Line; Zone 6)',
 'Elverson RoadDLR (Lewisham Branch); Zones 2/3)',
 'Embankment (Circle, District, Bakerloo, Northern Lines; Zone 1)',
 'Epping (Central Line; Zone 6)',
 'Euston (Northern, Victoria Line Lines; Zone 1)',
 'Euston Square (Circle, Hammersmith & City, Metropolitan Lines; Zone 1) ',
 'Fairlop (Central Line; Zone 5)',
 'Farringdon (Circle, Metropolitan, Hammersmith & City Lines; Zone 1)',
 'Finchley Central (Northern Line; Zone 4)',
 'Finchley Road (Jubilee, Metropolitan Lines; Zone 2)',
 'Finsbury Park (Victoria Line, Piccadilly Lines; Zone 2)',
 'Fulham Broadway (District Line; Zone 2)',
 'Gallions ReachDLR (Beckton Branch); Zone 3)',
 'Gants Hill (Central Line; Zone 5-6)',
 'Gloucester Road (Piccadilly, Circle, District Lines; Zone 1)',
 'Golders Green (Northern Line; Zone 3)',
 'Goldhawk Road (Hammersmith & City Line; Zone 2)',
 'Goodge Street (Northern Line; Zone 1)',
 'Grange Hill (Central Line; Zone 5)',
 'Great Portland Street (Circle, Hammersmith & City, Metropolitan Lines; Zone 1)',
 'Green Park (Jubilee, Victoria Line, Piccadilly Lines; Zone 1)',
 'Greenford (Central Line; Zone 4)',
 'Greenwich (DLR (Lewisham Branch); Zones 2/3)',
 'Gunnersbury (District Line; Zone 3) ',
 'Hainault (Central Line; Zone 5)',
 'Hammersmith (Hammersmith & City , District, Piccadilly Lines; Zone 2)',
 'Hampstead (Northern Line; Zones 2/3)',
 'Hanger Lane (Central Line; Zone 3)',
 'Harlesden (Bakerloo Line; Zone 3)',
 'Harrow & Wealdstone (Bakerloo Line; Zone 5)',
 'Harrow-on-the-Hill (Metropolitan Line; Zone 5)',
 'Hatton Cross (Piccadilly Line; Zones 5/6)',
 'Heathrow Terminal 4 (Piccadilly Line; Zone 6)',
 'Heathrow Terminals 1,2,3 (Piccadilly Line; Zone 6)',
 'Hendon Central (Northern Line; Zones 3/4)',
 'Heron Quays (DLR (Lewisham Branch); Zone 2)',
 'High Barnet (Northern Line; Zone 5)',
 'High Street Kensington (Circle, District Lines; Zone 1)',
 'Highbury & Islington (Victoria Line; Zone 2)',
 'Highgate (Northern Line; Zone 3)',
 'Hillingdon (Piccadilly, Metropolitan Lines; Zone 6)',
 'Holborn (Piccadilly, Central Lines; Zone 1)',
 'Holland Park (Central Line; Zone 2)',
 'Holloway Road (Piccadilly Line; Zone 2)',
 'Hornchurch (District Line; Zone 6)',
 'Hounslow Central (Piccadilly Line; Zone 4)',
 'Hounslow East (Piccadilly Line; Zone 4)',
 'Hounslow West (Piccadilly Line; Zone 5)',
 'Hyde Park Corner (Piccadilly Line; Zone 1) ',
 'Ickenham (Piccadilly, Metropolitan Lines; Zone 6)',
 'Island Gardens (DLR (Lewisham Branch); Zone 2) ',
 'Kennington (Northern Line; Zone 2)',
 'Kensal Green (Bakerloo Line; Zone 2)',
 'Kensington (Olympia) (District Line; Zone 2)',
 'Kentish Town (Northern Line; Zone 2)',
 'Kenton (Bakerloo Line; Zone 4)',
 'Kew Gardens (District Line; Zones 3/4)',
 'Kilburn (Jubilee Line; Zone 2)',
 'Kilburn Park (Bakerloo Line; Zone 2)',
 'King\'s Cross St Pancras (Circle, Metropolitan, Hammersmith & City, Victoria, Piccadilly, Northern Lines; Zone 1)',
 'Kingsbury (Jubilee Line; Zone 4)',
 'Knightsbridge (Piccadilly Line; Zone 1) ',
 'Ladbroke Grove (Hammersmith & City Line; Zone 2)',
 'Lambeth North (Bakerloo Line; Zone 1)',
 'Lancaster Gate (Central Line; Zone 1)',
 'Latimer Road (Hammersmith & City Line; Zone 2)',
 'Leicester Square (Piccadilly, Northern Lines; Zone 1)',
 'Lewisham (DLR (Lewisham Branch); Zones 2/3)',
 'Leyton (Central Line; Zone 3)',
 'Leytonstone (Central Line; Zones 3/4)',
 'Limehouse (DLR (Bank Branch); Zone 2)',
 'Liverpool Street (Central, Hammersmith & City, Circle, Metropolitan Lines; Zone 1)',
 'London Bridge (Northern, Jubilee Lines; Zone 1)',
 'Loughton (Central Line; Zone 6) ',
 'Maida Vale (Bakerloo Line; Zone 2)',
 'Manor House (Piccadilly Line; Zones 2/3)',
 'Mansion House (Circle, District Lines; Zone 1)',
 'Marble Arch (Central Line; Zone 1)',
 'Marylebone (Bakerloo Line; Zone 1)',
 'Mile End (Hammersmith & City, Central, District Lines; Zone 2)',
 'Mill Hill East (Northern Line; Zone 4)',
 'Monument (Circle, District Lines; Zone 1)',
 'Moor Park (Metropolitan Line; Zones 6/A)',
 'Moorgate (Northern, Circle, Metropolitan, Hammersmith & City Lines; Zone 1)',
 'Morden (Northern Line; Zone 4)',
 'Mornington Crescent (Northern Line; Zone 2)',
 'Mudchute (DLR (Lewisham Branch); Zone 2) ',
 'Neasden (Jubilee Line; Zone 3)',
 'New Cross (East London Line; Zone 2)',
 'New Cross Gate (East London Line; Zone 2)',
 'Newbury Park (Central Line; Zone 4)',
 'North Acton (Central Line; Zones 2/3)',
 'North Ealing (Piccadilly Line; Zone 3)',
 'North Greenwich (Jubilee Line; Zones 2/3)',
 'North Harrow (Metropolitan Line; Zone 5)',
 'North Wembley (Bakerloo Line; Zone 4)',
 'Northfields (Piccadilly Line; Zone 3)',
 'Northolt (Central Line; Zone 5)',
 'Northwick Park (Metropolitan Line; Zone 4)',
 'Northwood (Metropolitan Line; Zone 6)',
 'Northwood Hills (Metropolitan Line; Zone 6)',
 'Notting Hill Gate (Circle, Central, District Lines; Zones 1/2) ',
 'Oakwood (Piccadilly Line; Zone 5)',
 'Old Street (Northern Line; Zone 1)',
 'Osterley (Piccadilly Line; Zone 4)',
 'Oval (Northern Line; Zone 2)',
 'Oxford Circus (Victoria Line, Bakerloo, Central Lines; Zone 1) ',
 'Paddington (Circle, District, Hammersmith & City, Bakerloo Lines; Zone 1)',
 'Park Royal (Piccadilly Line; Zone 3)',
 'Parsons Green (District Line; Zone 2)',
 'Perivale (Central Line; Zone 4)',
 'Piccadilly Circus (Piccadilly, Bakerloo Lines; Zone 1)',
 'Pimlico (Victoria Line; Zone 1)',
 'Pinner (Metropolitan Line; Zone 5)',
 'Plaistow (Hammersmith & City, District Lines; Zone 3)',
 'Poplar (DLR; Zone 2)',
 'Preston Road (Metropolitan Line; Zone 4)',
 'Prince Regent (DLR (Beckton Branch); Zone 3)',
 'Pudding Mill LaneDLR (Stratford Branch); Zones 2/3)',
 'Putney Bridge (District Line; Zone 2) ',
 'Queen\'s Park (Bakerloo Line; Zone 4)',
 'Queensbury (Jubilee Line; Zone 2)',
 'Queensway (Central Line; Zone 1) ',
 'Ravenscourt Park (District Line; Zone 2)',
 'Rayners Lane (Piccadilly, Metropolitan Lines; Zone 5)',
 'Redbridge (Central Line; Zone 4)',
 'Regent\'s Park (Bakerloo Line; Zone 1)',
 'Richmond (District Line; Zone 4)',
 'Rickmansworth (Metropolitan Line; Zone A)',
 'Roding Valley (Central Line; Zone 5)',
 'Rotherhithe (East London Line; Zone 2)',
 'Royal Albert (DLR (Beckton Branch); Zone 3)',
 'Royal Oak (Hammersmith & City Line; Zone 2)',
 'Royal Victoria (DLR (Beckton Branch); Zone 3)',
 'Ruislip (Piccadilly, Metropolitan Lines; Zone 6)',
 'Ruislip Gardens (Central Line; Zone 5)',
 'Ruislip Manor (Piccadilly, Metropolitan Lines; Zone 6)',
 'Russell Square (Piccadilly Line; Zone 1) ',
 'Seven Sisters (Victoria Line; Zone 3)',
 'Shadwell (East London Line and DLR (Bank branch); Zone 2)',
 'Shepherd\'s Bush (Central, Hammersmith & City Lines; Zone 2)',
 'Shoreditch (East London Line; Zone 2)',
 'Sloane Square (Circle, District Lines; Zone 1)',
 'Snaresbrook (Central Line; Zone 4)',
 'South Ealing (Piccadilly; Zone 3)',
 'South Harrow (Piccadilly Line; Zone 5)',
 'South Kensington (Piccadilly, Circle, District Lines; Zone 1)',
 'South Kenton (Bakerloo Line; Zone 4)',
 'South Quay (DLR (Lewisham Branch); Zone 2)',
 'South Ruislip (Central Line; Zone 5)',
 'South Wimbledon (District Line; Zones 3/4)',
 'South Woodford (Central Line; Zone 4)',
 'Southfields (District Line; Zone 3)',
 'Southgate (Piccadilly Line; Zone 4)',
 'Southwark (Jubilee Line; Zone 1)',
 'St. James\'s Park (Circle, District Lines; Zone 1)',
 'St John\'s Wood (Jubilee Line; Zone 2)',
 'St. Paul\'s (Central Line; Zone 1)',
 'Stamford Brook (District Line; Zone 2)',
 'Stanmore (Jubilee Line; Zone 5)',
 'Stepney Green (Hammersmith & City, District Lines; Zone 2)',
 'Stockwell (Victoria Line, Northern Lines; Zone 2)',
 'Stonebridge Park (Bakerloo Line; Zone 3)',
 'Stratford (Jubilee, Central Lines, DLR (Stratford Branch; Zone 3)',
 'Sudbury Hill (Piccadilly Line; Zone 4)',
 'Sudbury Town (Piccadilly Line; Zone 4)',
 'Surrey Quays (East London Line; Zone 2)',
 'Swiss Cottage (Jubilee Line; Zone 2) ',
 'Temple (Circle, District Lines; Zone 1)',
 'Theydon Bois (Central Line; Zone 6)',
 'Tooting Bec (Northern Line; Zone 3)',
 'Tooting Broadway (Northern Line; Zone 3)',
 'Tottenham Court Road (Northern, Central Lines; Zone 1)',
 'Tottenham Hale (Victoria Line; Zone 3)',
 'Totteridge & Whetstone (Northern Line; Zone 4)',
 'Tower Gateway (DLR (Bank branch); Zone 1)',
 'Tower Hill (Circle, District Lines; Zone 1)',
 'Tufnell Park (Northern Line; Zone 2)',
 'Turnham Green (Piccadilly, District Lines; Zones 2/3)',
 'Turnpike Lane (Piccadilly Line; Zone 3) ',
 'Upminster (District Line; Zone 6)',
 'Upminster Bridge (District Line; Zone 6)',
 'Upney (District Line; Zone 4)',
 'Upton Park (District, Hammersmith & City Lines; Zone 3)',
 'Uxbridge (Piccadilly, Metropolitan Lines; Zone 6) ',
 'Vauxhall (Victoria Line; Zones 1/2)',
 'Victoria (Victoria Line, Circle, District Lines; Zone 1) ',
 'Walthamstow Central (Victoria Line; Zone 3)',
 'Wanstead (Central Line; Zone 4)',
 'Wapping (East London Line; Zone 2)',
 'Warren Street (Northern Line; Zone 1)',
 'Warwick Avenue (Bakerloo Line; Zone 2)',
 'Waterloo (Waterloo & City, Bakerloo, Northern, Jubilee Lines; Zone 1)',
 'Watford (Metropolitan Line; Zone A)',
 'Wembley Central (Bakerloo Line; Zone 4)',
 'Wembley Park (Jubilee, Metropolitan Lines; Zone 4)',
 'West Acton (Central Line; Zone 3)',
 'West Brompton (District Line; Zone 2)',
 'West Finchley (Northern Line; Zone 4)',
 'West Ham (Hammersmith & City, District, Jubilee Lines; Zone 3)',
 'West Hampstead (Jubilee Line; Zone 2)',
 'West Harrow (Metropolitan Line; Zone 5)',
 'West India Quay (DLR (Lewisham Branch); Zone 2)',
 'West Kensington (District Line; Zone 2)',
 'West Ruislip (Central Line; Zone 6)',
 'Westbourne Park (Hammersmith & City Line; Zone 2)',
 'Westferry (DLR (Bank Branch); Zone 2)',
 'Westminster (Jubilee, Circle, District Lines; Zone 1)',
 'White City (Central Line; Zones 2/3)',
 'Whitechapel (East London, Hammersmith & City, District Lines; Zone 2)',
 'Willesden Green (Jubilee Line; Zones 2/3)',
 'Willesden Junction (Bakerloo Line; Zone 3)',
 'Wimbledon (District Line; Zone 3)',
 'Wimbledon Park (District Line; Zone 3)',
 'Wood Green (Piccadilly Line; Zone 3)',
 'Woodford (Central Line; Zone 4)',
 'Woodside Park (Northern Line; Zone 4) ',
 );
 return $array;
}

?>